template: Hello, %s!

name: Madhukar

# server details
server:
  type: server
  
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
  requestLog:
    timeZone: UTC
    appenders:
      - type: file
        currentLogFilename: ./logs/requests.log
        threshold: ALL
        archive: true
        archivedLogFilenamePattern: ./logs/requests-%d.log.gz
        archivedFileCount: 5
        timeZone: UTC
#logging
logging:
  level: INFO
  appenders:
    - type: file
      currentLogFilename: ./logs/application.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: ./logs/application-%d.log
      archivedFileCount: 2
      timeZone: UTC

#database
database:
  driverClass: org.h2.Driver
  user: sa
#  password:
  url: jdbc:h2:./persondb
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute

